# Generated by Django 5.2.17 on 2026-10-04 13:47

import core.models
import django.db.models.deletion
import django.utils.timezone
import news.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="title (French)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="title (English)"
                    ),
                ),
                ("body_fr", models.TextField(blank=True, verbose_name="text (French)")),
                (
                    "body_en",
                    models.TextField(blank=True, verbose_name="text (English)"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="publication date",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="published"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-pk"],
            },
            bases=(core.models.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=news.models.image_path)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="news.article",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ArticleVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="YouTube or Vimeo link")),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="news.article",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
            },
        ),
    ]
