# Generated by Django 5.2.17 on 2026-10-04 13:47

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="full name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("phone", models.CharField(max_length=30, verbose_name="phone number")),
                ("message", models.TextField(max_length=5000, verbose_name="message")),
                ("language", models.CharField(default="fr", max_length=2)),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("replied", "Replied")],
                        db_index=True,
                        default="new",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True, verbose_name="organisation description (French)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, verbose_name="organisation description (English)"
                    ),
                ),
                (
                    "mission_fr",
                    models.TextField(blank=True, verbose_name="our mission (French)"),
                ),
                (
                    "mission_en",
                    models.TextField(blank=True, verbose_name="our mission (English)"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            bases=(core.models.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ContactReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=10000)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="core.contactmessage",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sent_at"],
            },
        ),
    ]
