# Generated by Django 5.2.17 on 2026-10-04 13:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import qa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("file", models.FileField(upload_to=qa.models.document_path)),
                ("original_filename", models.CharField(max_length=255)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("ocr_page_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="QAMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "user"), ("assistant", "assistant")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("citations", models.JSONField(blank=True, default=list)),
                ("answered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.PositiveIntegerField()),
                ("index", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("vec_fr", django.contrib.postgres.search.SearchVectorField(null=True)),
                ("vec_en", django.contrib.postgres.search.SearchVectorField(null=True)),
                (
                    "vec_simple",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="qa.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document_id", "index"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["vec_fr"], name="qa_chunk_vec_fr"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["vec_en"], name="qa_chunk_vec_en"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["vec_simple"], name="qa_chunk_vec_simple"
                    ),
                ],
            },
        ),
    ]
